Improve logging
RaaLabs/Connectors.Modbus pull request #42
Opened 2022-11-10 20:43 UTC by rafaelschlatter

## Summary

Summary of the PR here. The GitHub release description is created from this comment so keep it nice and descriptive.

Remember to remove sections that you don't need or use.

### Added

- Describe the added features

### Changed

- Describe the outwards facing code change

### Fixed

- Describe the fix and the bug

### Removed

- Describe what was removed and why

### Security

- Describe the security issue and the fix

### Deprecated

- Describe the part of the code being deprecated and why

2022-11-29 23:03 UTC, srudaa requested changes
Not able to throw if there is no connection or connection is lost. Furthermore, might consider to make the logs easier to understand and not include the stack trace for known exceptions

2022-11-29 23:03 UTC, srudaa commented on Source/Bridge/ModbusBridge.cs
> +                            _ => { });
I don't understand this part. Furthermore, this will also not throw if connection is lost

2022-12-02 08:49 UTC, thotokraa requested changes
Looks good. Fix the connectivity issue, then I'll approve.

2022-12-02 08:49 UTC, thotokraa commented on Source/Bridge/ModbusBridge.cs
> +                            _ => { });
Well spotted! I believe this can be fixed by rethrowing the exception on line 73.

2022-12-12 14:33 UTC, merged